import remarkGfm from "remark-gfm";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import rehypePrettyCode from "rehype-pretty-code";
import type { MDXRemoteProps } from "next-mdx-remote/rsc";
import { beforthCodeTheme } from "@/lib/code-theme";
import { H1, H2, H3, H4, H5, H6 } from "@/components/md/Headings";
import { CodeBlock } from "@/components/md/CodeBlock";
import { Callout } from "@/components/md/Callout";
import { Tabs, Tab, CodeGroup } from "@/components/md/Tabs";

/**
 * Shared remark/rehype pipeline for every doc page.
 * Heading ids produced here (via rehype-slug) match the TOC ids generated by
 * lib/headings.ts (both use github-slugger).
 */
type MdxOptions = NonNullable<MDXRemoteProps["options"]>["mdxOptions"];

export const mdxOptions: MdxOptions = {
  remarkPlugins: [remarkGfm],
  rehypePlugins: [
    [
      rehypePrettyCode,
      {
        theme: beforthCodeTheme,
        keepBackground: false,
        defaultLang: "text",
        bypassInlineCode: true,
      },
    ],
    rehypeSlug,
    [
      rehypeAutolinkHeadings,
      {
        behavior: "append",
        properties: { className: ["anchor"] },
      },
    ],
  ],
};

/**
 * Components available inside .mdx files. Plain .md files get the same set,
 * plus default markdown rendering styled by globals.css.
 */
export const mdxComponents = {
  h1: H1,
  h2: H2,
  h3: H3,
  h4: H4,
  h5: H5,
  h6: H6,
  pre: CodeBlock,
  Callout,
  Tabs,
  Tab,
  CodeGroup,
} as MDXRemoteProps["components"];
